# Generated by Django 3.2.3 on 2021-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_info',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=40)),
                ('team', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
