# Generated by Django 3.2.3 on 2021-06-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player_info',
            table=None,
        ),
    ]
