# Generated by Django 3.2.3 on 2021-06-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_player_info_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player_name',
        ),
    ]
